config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'
  
  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :children

  namespace :api do
    resources :children do
      resources :posts, only: [:index]
    end

    resources :posts, except: [:index]
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  title       :string
#  child_id    :integer
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Category < ActiveRecord::Base
  belongs_to :child
end

app/models/child.rb
# == Schema Information
#
# Table name: children
#
#  id          :integer          not null, primary key
#  name        :string
#  user_id     :string
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Child < ActiveRecord::Base
  has_one :photo, as: :imageable
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id                 :integer          not null, primary key
#  photo_file_name    :string
#  photo_content_type :string
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#  imageable_id       :integer
#  imageable_type     :string
#  created_at         :datetime
#  updated_at         :datetime
#

class Photo < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true

  has_attached_file :photo, styles: {
    big: "600x600>",
    medium: "300x300>",
    small: "50x50#"
  }
  validates_attachment_content_type(
    :photo,
    content_type: /\Aimage\/.*\Z/
  )
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}
  validates :passwordConfirm, length: { minimum: 6, allow_nil: true}
  validate :passwords

  has_one :photo, as: :imageable

  after_initialize :ensure_session_token
  attr_reader :password, :passwordConfirm


  def self.generate_session_token
    begin
      token = SecureRandom.urlsafe_base64
    end until !self.exists?(:session_token => token)
    token
  end

  def self.find_by_credentials(email, password)
    @user = self.find_by_email(email)
    if @user.nil? || !@user.is_password?(password)
      @user = nil
    end
    @user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def passwordConfirm=(passwordConfirm)
    @passwordConfirm = passwordConfirm
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def passwords
    unless @password == @passwordConfirm
      errors.add(:passwords, " did not match")
    end
  end
end

app/controllers/api/children_controller.rb
class Api::ChildrenController < ApplicationController
  def index
    @children = Child.all
    render json: @children
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :csrf_input
  helper_method :current_user
  helper_method :login!
  helper_method :logout!
  helper_method :logged_in?

  def csrf_input
    html = <<-HTML
    <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
    HTML
    html.html_safe
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end


  private
  def user_params
    params.require(:user).permit(:username, :password, :passwordConfirm, :email)
  end

  def require_current_user!
    unless logged_in?
      redirect_to new_session_url
    end
  end

  private

  def photo_params
    params.require('photo').permit(:photo, :imageable_id, :imageable_type, :photo_file_name, :photo_content_type, :photo_file_size, :photo_updated_at)
  end
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  def show
    @child = Child.find(params[:id])
    render :show
  end

  def new
    @child = Child.new()
    render :new
  end

  def create
    @child = Child.new()
    build_params = child_params
    build_params[:user_id] = current_user.id
    build_photo_params = {}
    if @child.update(child_params)
      build_photo_params[:photo] = params[:child][:photo]
      build_photo_params[:imageable_type] = 'Child'
      build_photo_params[:imageable_id] = @child.id
      @photo = Photo.create(build_photo_params)
      redirect_to child_path(@child)
    else
      redirect_to childs_path
    end
  end

  private

  def child_params
    params.require('child').permit(:name, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_credentials(user_params[:email], user_params[:password])
    if @user.nil?
      flash.now[:errors] = ["Email not found or invalid password"]
      @user = User.new(user_params)
      render :new
    else
      login!(@user)
      redirect_to root_url
    end
  end

  def new
    @user = User.new
    render :new
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_current_user!

  def root
    render :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user!, except: [:create, :new]

  def index # do this with javascript
    render :index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def edit # do this with javascript
    @user = User.find(params[:id])
    render :edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      User.new(user_params.merge(id: params[:id]))
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.username == 'guest'
      flash.now[:errors] = ["Cannot delete guest account."]
      render :show
    elsif @user.id == current_user.id
      logout!
      @user.destroy
      redirect_to new_session_url
    else
      @user.destroy
      render :index
    end
  end

  def show # do this with javascript
    @user = User.find(params[:id])
    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/children/new.html.erb
<%= form_for @child, :url => children_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :photo %>
  <%= form.text_field :name %>
  <%= form.text_area :description %>
  <%= form.submit %>
<% end %>

app/views/children/show.html.erb
<h1><%= @child.name %></h1>
<p><%= @child.description %></p>
<%= image_tag @child.photo.photo.url(:big) %>

app/views/layouts/_errors.html.erb
<% unless flash[:errors].nil? %>
  <div class="container errors">
    <ul class="list-group col-md-4">
      <% flash[:errors].each do |error| %>
        <li class="list-group-item"><%= error %></li>
      <% end %>
    </ul>
    <div class="col-md-8"></div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" id="nav-bg"> <!-- removed navbar-default -->
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="color: #FEF9ED">LilaFix</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div id="nav-el"></div>
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <!-- <li><a href="#">"Current Category Name"</a></li> -->
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      <!-- will add search if time permits -->
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><a href="<%= session_url %>" data-method="delete">Log Out</a></li>
        <% else %>
          <li><a href="<%= new_user_url %>">Sign Up</a></li>
          <li><a href="<%= new_session_url %>">Log In</a></li>
        <% end %>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<!-- Button trigger modal -->

<!-- Modal -->
<div id="app-modal"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LilaFix</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%# favicon_link_tag 'favicon.png' %>
  <% if current_user %>
    <script>
      window.LilaFixApp._current_user_id = <%= current_user.id %>
    </script>
  <% end %>
</head>
<body>

<%= render partial: 'layouts/header' %>
<%= render partial: 'layouts/errors' %>
<%= yield %>

</body>
</html>

app/views/static_pages/root.html.erb
<div class="backdrop">
  <div id="main"></div>
</div>
<script>
  $(document).ready(function(){
    LilaFixApp.initialize();
  });
</script>

app/views/users/_form.html.erb
<% if @user.persisted? %>
  <% url = user_url(@user) %>
  <% button_val = "Update #{@user.username}" %>
<% else %>
  <% url = users_url %>
  <% button_val = "Submit" %>
<% end %>
<div class="container">
  <div class="col-md-3"></div>
  <form action="<%= url %>" class="form-horizontal auth-control col-md-6" method="POST">
    <div class="form-group">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    </div>
    <% if @user.persisted? %>
      <input type="hidden" name="_method" value="PATCH">
    <% end %>

    <div class="form-group" style="margin-top: 15px">
      <label for="username_field" class="col-md-2 control-label">Username:</label>
      <div class="col-md-10">
        <input type="text" class="form-control" id="username_field" name="user[username]" value="<%= @user.username %>" placeholder="john_doe">
      </div>
    </div>
    <div class="form-group">
      <label for="email_field" class="col-md-2 control-label">Email:</label>
      <div class="col-md-10">
        <input type="text" class="form-control" id="email_field" name="user[email]" value="<%= @user.email %>" placeholder="johndoe@example.com">
      </div>
    </div>
    <% unless @user.persisted? %>
      <div class="form-group">
        <label for="password_field" class="col-md-2 control-label">Password:</label>
        <div class="col-md-10">
          <input type="password" class="form-control" id="password_field" name="user[password]" placeholder="Password">
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-2"></div>
        <div class="col-md-10">
          <input type="password" class="form-control" id ="passwordConfirm_field" name="user[passwordConfirm]" placeholder="Confirm Password">
        </div>
      </div>
    <% end %>
    <div class="form-group">
      <div class="col-md-2"></div>
      <div class="col-md-10">
        <input type="submit" class="form-control" value="<%= button_val %>">
      </div>
    </div>
  </form>
  <div class="col-md-3"></div>
</div>

app/views/users/edit.html.erb
<h1 class="page-title">Edit <%= @user.username %></h1>
<%= render partial: "form" %>

app/views/users/index.html.erb
<h1>All the users!</h1>
<ol>
  <% User.all.each do |user| %>
    <li>
      <%= link_to user.username, user_url(user) %>
    </li>
  <% end %>
</ol>

app/views/users/new.html.erb
<h1 class="page-title">Sign up</h1>
<%= render partial: "form" %>

app/views/users/show.html.erb
<h1 class="page-title"><%= @user.username %></h1>
<h3>Username: <%= @user.username %></h3>
<h3>Email: <%= @user.email %></h3>
<% if !current_user.nil? && @user.id == current_user.id %>
  <%= button_to "Edit #{@user.username}", edit_user_url(@user), method: :get %>
  <%= button_to "Delete #{@user.username}", user_url(@user), method: :delete %>
<% end %>
<%= button_to "Index", users_url, method: :get %>